server:
  port: 8006

spring:
  application:
    name: consul-provider-payment

  cloud:
    consul:
      host: 39.96.48.41
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true