server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service

  cloud:
    nacos:
      discovery:
        server-addr: 39.96.48.41:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 9719
      datasource:
        ds1:
          nacos:
            server-addr: 39.96.48.41:8848
            dataid: cloudalibaba-sentinel-service
            groupid: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'