server:
  port: 84
spring:
  application:
    name: nacos-order-consumer

  cloud:
    nacos:
      discovery:
        server-addr: 39.96.48.41:8848

    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

#消费者将要去访问的微服务名,（注册进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider


#对feign的支持
feign:
  sentinel:
    enabled: true
