server:
  port: 3344

spring:
  application:
    name: cloud-config-center   #注册进eureka的服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lwg729/cloud01.git  #Github上面的git仓库名字

          #搜索目录
          search-paths:
            - cloud01

      #读取分支
      label: master

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'