server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 39.96.48.41:8848


management:
  endpoints:
    web:
      exposure:
        include: '*'
