server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka   #单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: hystrix-order80   #服务名称修改
    prefer-ip-address: true  #访问信息有ip显示

# 开启feign客户端支持hystrix属性 因为没有向eureka中注册,是一个feign客户端
feign:
  hystrix:
    enabled: true